version: "3"

#networks:
#  network-proxy:
#    external: true

services:
  api:
    hostname: api
    build:
      dockerfile: api/Dockerfile
      context: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
  #    networks:
  #      - network-proxy
  frontend:
    hostname: frontend
    build:
      dockerfile: frontend_app/Dockerfile
      context: ./
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
  #    networks:
  #      - network-proxy
  db:
    hostname: db
    build:
      dockerfile: db/Dockerfile
      context: ./
    environment:
      POSTGRES_USER: 'placeholder_user'
      POSTGRES_PASSWORD: 'placeholder_pass'
      POSTGRES_DB: 'placeholder_db'
    ports:
      - "5432:5432"
    volumes:
      - /home/paolo/git/kcp-registration/db-data:/var/lib/postgresql/data
#    networks:
#      - network-proxy
volumes:
  db-data:
